[package]
name = "autograph"
version = "0.0.2"
authors = ["Charles R Earp <charles.r.earp@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "Machine Learning Library for Rust"
homepage = "https://github.com/charles-r-earp/autograph"
repository = "https://github.com/charles-r-earp/autograph"
keywords = ["neural-networks", "machine-learning", "cuda", "deep-learning", "autograd"]
categories = ["science"]
readme = "README.md"

[dependencies]
autograph_derive = { path = "autograph_derive", optional = true }
onednn-sys = { git = "https://github.com/charles-r-earp/onednn-sys" }
cpp = "0.5.4"
rustacuda = { version = "0.1.2", optional = true }
cuda-sys = { version = "0.2.0", optional = true }
cuda-cudnn-sys = { git = "https://github.com/charles-r-earp/cuda-cudnn-sys", optional = true }
hip-sys = { git = "https://github.com/charles-r-earp/hip-sys", optional = true }
miopen-sys = { git = "https://github.com/charles-r-earp/miopen-sys", optional = true }
num-traits = "0.2.11"
proxy-enum = "0.2.0"
ndarray = "0.13.1"
byteorder = { version = "1.3.4", optional = true }
flate2 = { version = "1.0.14", optional = true }
reqwest = { version = "0.9.22", optional = true }
rand = "0.7.3"
rand_distr = "0.2.2"
argmm = "0.1.0"
serde = { version = "1.0.114", features=["derive"] }
bincode = "1.3.1"

[build-dependencies]
cmake = "0.1.42"
cpp_build = "0.5.4"
cc = "1.0.55"

[features]
default = ["derive", "datasets"]
derive = ["autograph_derive"]
datasets = ["byteorder", "flate2", "reqwest"]
cuda = ["rustacuda", "cuda-sys", "cuda-cudnn-sys"]
rocm = ["hip-sys", "miopen-sys"]
# dev use only!
compile-kernels = []

[dev-dependencies]
rand = { version = "0.7.3", features=["small_rng"] }
approx = "0.3.2"
tch = "0.1.7"
criterion = "0.3.2"
argparse = "0.2.2"

[[bench]]
name = "bench_lenet5"
harness = false



