[package]
name = "autograph_derive"
version = "0.0.1"
authors = ["Charles R Earp <charles.r.earp@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "Procedural macro crate for autograph"
homepage = "https://github.com/charles-r-earp/autograph"
repository = "https://github.com/charles-r-earp/autograph"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.33", features = ["full"] }
quote = "1.0.7"
proc-macro2 = "1.0.18"

#[dev-dependencies]
#autograph = { path = "../" }
#ndarray = "0.13.1"
